// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efyguenaswmctvpnxgbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmeWd1ZW5hc3dtY3R2cG54Z2JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODczNjQsImV4cCI6MjA3MTI2MzM2NH0.MoutrLm3LXBgSDBMdRRRtBaIwXb-F9zkWLGK7I9O-QU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});